# Generated by Django 3.2.7 on 2021-09-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creating')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
