# Generated by Django 3.2.7 on 2021-09-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='User ID'),
        ),
    ]
