# Generated by Django 3.2.7 on 2021-09-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('url', models.URLField(verbose_name='URL задачи')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задача',
            },
        ),
    ]
