# Generated by Django 3.2.7 on 2021-09-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymantHictory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Выведено: ')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата вывода')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'История платежей',
                'verbose_name_plural': 'Истории платежей',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
