# Generated by Django 3.2.7 on 2021-09-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_auto_20210930_0353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymantHictory',
            new_name='PaymantHistory',
        ),
    ]
