# Generated by Django 3.2.7 on 2021-09-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_rename_paymanthictory_paymanthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='paymanthistory',
            name='date',
            field=models.DateTimeField(verbose_name='Дата вывода'),
        ),
    ]
