# Generated by Django 3.2.7 on 2021-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_task_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
