# Generated by Django 3.2.7 on 2021-09-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_auto_20210930_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bon',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма для выполнения'),
            preserve_default=False,
        ),
    ]
