# Generated by Django 3.2.7 on 2021-10-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone number'),
        ),
    ]
